/**
 * RealWorld Conduit API
 * Conduit API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Profile } from './profile.model';


export interface Comment { 
    id: number;
    createdAt: string;
    updatedAt: string;
    body: string;
    author: Profile;
}

