/**
 * API
 * API Description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ArticleCommentDto } from './articleCommentDto.model';


export interface CreateArticleCommentDto { 
    comment: ArticleCommentDto;
}

